---

- name: install packages
  sudo: true
  apt: >
      name={{ item }}
      state=latest
      update_cache=true
  with_items: firefox_packages
  tags: packages

- name: install templates
  template: >
      src={{ item }}.j2
      dest={{ ansible_env.HOME }}/{{ item }}
      mode=640
  with_items: firefox_templates

- name: install user prefs files
  sudo: true
  copy: >
      src={{ item }}
      dest={{ firefox_pref_path }}/{{ item }}
      mode=644
  with_items: firefox_files
