---

- name: rm packages
  sudo: true
  apt: >
      name={{ item }}
      state=absent
      purge=true
  with_items: firefox_packages
  tags: packages

- name: rm pref_path files
  file: >
      path={{ firefox_pref_path }}/{{ item }}
      state=absent
  with_items: firefox_files
