# playbook to install desktop env

---

- name: do bmoar
  hosts: bmoar
  roles:
      - { role: secrets, tags: secrets }
      - { role: term, tags: term }
      - { role: ssh_client, tags: ssh_client }
      - { role: git, tags: git }
      - { role: vim, tags: vim }
      - { role: truecrypt, tags: truecrypt }
      - { role: passman, tags: passman }
        # require window manager
      - { role: xorg, tags: xorg }
      - { role: i3, tags: i3 }
      - { role: firefox, tags: firefox }
