# playbook to install desktop env

---

- name: do bmoar
  hosts: bmoar
  roles:
      - { role: secrets, tags: secrets }
      - { role: term, tags: term }
      - { role: ssh_client, tags: ssh_client }
