---

- name: install VM packages
  sudo: true
  apt: >
    name={{ item }}
    state=latest
    update_cache=true
  with_items: vms_packages
  tags: packages

- name: add {{ ansible_env.USER }} to VM groups
  sudo: true
  user: >
    name={{ ansible_env.USER }}
    append=true
    groups=libvirtd
