---

- name: install sysctl template
  sudo: True
  template: >
      src="64-{{ ansible_env['USER'] }}-magic.conf.j2"
      dest="/etc/sysctl.d/64-{{ ansible_env['USER'] }}-magic.conf"
  register: sysctl_template_out
  tags: templates

- name: trigger sysctl reboot when sysctl_mod_disabled becomes 0
  sudo: True
  command: >
      /bin/true
  notify: sysctl_reboot
  when: sysctl_template_out.changed == True and sysctl_mod_disabled == 0

- name: install hostfile
  sudo: true
  template: >
      src=hosts.j2
      dest=/etc/hosts
  tags: templates
