---

- name: install packages
  sudo: true
  apt: >
      name={{ item }}
      state=present
      update_cache=true
  tags: packages
  with_items: ssh_client_packages

- name: install templates
  template: >
      src={{ item.name }}.j2
      dest={{ ssh_client_dot_path }}/{{ item.name }}
      mode={{ item.mode }}
  with_items: ssh_client_templates
