---

- name: add neovim ppa
  apt_repository: >
      repo='ppa:neovim-ppa/unstable'
      state=present

- name: install packages
  sudo: true
  apt: >
      name={{ item.name }}
      state=latest
      update_cache=true
  with_items: vim_packages
  tags: packages

- name: install neovim python extensions
  sudo_user: "{{ ansible_env.USER }}"
  pip: >
      name=neovim
      state=present
      extra_args="--user"
  tags: packages

- name: add vim colors dir
  file: >
    path={{ ansible_env.HOME }}/.vim/{{ item }}
    state=directory
    mode=770
  with_items: vim_dirs

- name: install templates
  template: >
      src={{ item }}.j2
      dest={{ ansible_env.HOME }}/{{ item }}
      mode=640
  with_items: vim_templates

- name: install files
  copy: >
      src={{ item }}
      dest={{ ansible_env.HOME }}/{{ item }}
      mode=640
  with_items: vim_files

- name: add vundle repo
  git: >
    repo='https://github.com/gmarik/Vundle.vim.git'
    dest={{ ansible_env.HOME }}/.vim/bundle/Vundle.vim
    update=false

- name: symlink for neovim
  file: >
      src="{{ ansible_env.HOME }}/.{{ item }}"
      dest="{{ ansible_env.HOME }}/.n{{ item }}"
      state=link
  with_items:
      - vimrc
      - vim
