---

- name: clone truecrypt repo
  git: >
    repo={{ git_base_repo }}/truecrypt-archive
    version=7.1a
    dest={{ ansible_env.HOME }}/git/truecrypt-archive
  tags: packages

- name: check truecrypt mount point
  sudo: True
  stat: >
    path={{ ansible_env.HOME }}/mnt/truecrypt0
  register: truecrypt_mount_point_rc

- name: ensure truecrypt mount point exists
  sudo: True
  file: >
    path={{ ansible_env.HOME }}/mnt/truecrypt0
    state=directory
    mode=755
  when: truecrypt_mount_point_rc.exists | default(False) | bool == False
